DROP DATABASE IF EXISTS Banco;
CREATE DATABASE Banco;
CREATE USER IF NOT EXISTS 'Banco'@'localhost' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS 'Banco'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON Banco.* TO 'Banco'@'%';
GRANT ALL PRIVILEGES ON Banco.* TO 'Banco'@'localhost';
